### ISSUE TITLE
Can't use Pre trained model

### ISSUE THREAD

**Issue by mehar50** [TwentyBN/smth-smth-v2-baseline-with-models#7]
When I am trying to load model (model_best.pth.tar) file in 3rd step I got this error
**RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location='cpu' to map your storages to the CPU.**
Please help me to fix it

**Comment by raghavgoyal14** [comment]
Seems like you're not using GPUs, so just substitute `torch.load()` call in the code with 
`torch.load(<path-to-model_best.pth.tar>, map_location=torch.device('cpu'))`

ref: https://pytorch.org/docs/stable/torch.html#torch.load

Hope this helps!

**Comment by mehar50** [comment]
Error fixed
I have no words to thank you ….Bundle of thanks for answering my query

**Comment by mehar50** [comment]
when I am trying to load model using this code I got error
 **TypeError: 'dict' object is not callable**
code:model = MultiColumn(config['num_classes'], column_cnn_def.Model, int(config["column_units"]))
model.eval();

print("=> loading checkpoint")
checkpoint=torch.load(r"C:\Users\Bilal\PycharmProjects\FYP\trained_models\pretrained\model3D_1\model_best.pth.tar", map_location={'cuda:0': 'cpu'})
checkpoint['state_dict'] = remove_module_from_checkpoint_state_dict(
                                              checkpoint['state_dict'])
model.load_state_dict(checkpoint['state_dict'])
print(r"C:\Users\Bilal\PycharmProjects\FYP\trained_models\pretrained\model3D_1\model_best.pth.tar '{}' (epoch {} )"
      .format(r"C:\Users\Bilal\PycharmProjects\FYP\trained_models\pretrained\model3D_1\model_best.pth.tar", checkpoint('epoch 55')))

**Comment by raghavgoyal14** [comment]
Can you post the complete traceback with line numbers? I can't understand where the error is.

**Comment by mehar50** [comment]
Thanks, Problem solved I was using the wrong parenthesis. one should not use built-in type names as variable names, to prevent this error.
I modify code such as

**model = MultiColumn(config['num_classes'], column_cnn_def.Model, int(config["column_units"]))
model.eval();

print("=> loading checkpoint")
checkpoint=torch.load(r"C:\Users\Bilal\PycharmProjects\FYP\trained_models\pretrained\model3D_1\model_best.pth.tar", map_location={'cuda:0': 'cpu'})
checkpoint['state_dict'] = remove_module_from_checkpoint_state_dict(
                                              checkpoint['state_dict'])
model.load_state_dict(checkpoint['state_dict'])
print("=> loaded checkpoint 'C:/Users/Bilal/PycharmProjects/FYP/trained_models/pretrained/model3D_1/model_best.pth.tar' (epoch 55)"
      .format(r"C:\Users\Bilal\PycharmProjects\FYP\trained_models\pretrained\model3D_1\model_best.pth.tar", checkpoint['epoch']))**

**Comment by mehar50** [comment]
Hello sir when am trying to load data I got an error by running following block of code, Here
am confused that what dose 'data folder' means is it require data-set folder path ?what are clip size nclips and step_size_val please help me
**val_data = VideoFolder(root=config['data_folder'],
json_file_input=config['json_data_val'],
 json_file_labels=config['json_file_labels'],
                       clip_size=config['clip_size'],
                       nclips=config['nclips_val'],
                       step_size=config['step_size_val'],
                       is_val=True,
                       transform_pre=transform_eval_pre,
                       transform_post=transform_post,
                       get_item_id=True,
                       )
dict_two_way = val_data.classes_dict**

**Comment by mehar50** [comment]
When I am trying to follow the steps of notebook **https://github.com/TwentyBN/smth-smth-v2-baseline-with-models/blob/master/notebooks/get_prediction_from_pre_trained_model.ipynb**
But in 4th step I have an error that is **FileNotFoundError: [Errno 2] No such file or directory: '/data-ssd1/20bn-something-something-v2/annotations/something-something-v2-labels.json'**
I have downloaded json files and dataset from 20BN site but how I can provide path,
Sir please help me I don't have no experience ML ,I am electronics engineering student I have to run this pre-trained model before due date ,I shall be thankful to you

**Comment by raghavgoyal14** [comment]
You just have to modify the config file located on your machine: `"configs/pretrained/config_model1.json"`

and provide correct path (to where you have downloaded these files):

- path to data: `data_folder`
- path to data JSONs: `json_data_train`, `json_data_val`, `json_data_test`
- path to label JSON: `json_file_labels`


ref: https://github.com/TwentyBN/smth-smth-v2-baseline-with-models#modify-config-file-to-include-the-above-paths

**Comment by mehar50** [comment]
Thanks for the reply , Error is solved

**Comment by mehar50** [comment]
When I am trying to get data in required format I got this error
using this code
**elected_indx = np.random.randint(len(val_data))
selected_indx = 136
input_data, target, item_id = val_data[selected_indx]
input_data = input_data.unsqueeze(0)
print("Id of the video sample = 166766".format(item_id))
print("True label --> 57 ({})".format(target, dict_two_way[target]))**
---------
**Traceback (most recent call last):
  File "C:/Users/Bilal/PycharmProjects/FYP/Main1.py", line 76, in <module>
    input_data, target, item_id = val_data[selected_indx]
  File "C:\Users\Bilal\PycharmProjects\FYP\data_loader_av.py", line 47, in __getitem__
    reader = av.open(item.path)
  File "av\container\core.pyx", line 226, in av.container.core.open
  File "av\container\core.pyx", line 148, in av.container.core.Container.__cinit__
  File "av\container\core.pyx", line 180, in av.container.core.Container.err_check
  File "av\utils.pyx", line 107, in av.utils.err_check
av.AVError: [Errno 2] No such file or directory: 'D:\\data\\20bn-something-something-v2-00\\166241.webm'**

**Comment by raghavgoyal14** [comment]
Did you download the data and extract files using `cat 20bn-something-something-v2-?? | tar zx`?
ref: https://20bn.com/datasets/something-something/v2#download

Also, did you set the path to extracted videos (`data_folder`) correctly in your config file?

**Comment by mehar50** [comment]
I download the dataset and the path of 'data folder ' is correct , but I don't know how to extract data?Please suggest me the method

**Comment by raghavgoyal14** [comment]
Go in the data directory (where you've downloaded the dataset) and run this command `cat 20bn-something-something-v2-?? | tar zx`

It will extract the videos in a separate folder. Provide the path to that folder in the config file.

**Comment by mehar50** [comment]
Sir when I run this command in pycharm or CMD I got this error 
**C:\Users\Bilal\PycharmProjects\FYP>cat 20bn-something-something-v2-?? | tar zx
'cat' is not recognized as an internal or external command,
operable program or batch file.**

**Comment by raghavgoyal14** [comment]
Seems like you are using Windows OS. This command is for Unix-based systems.
Can you search for an equivalent command in Windows?

I don't have access to a Windows machine and can't provide support for this.

**Comment by mehar50** [comment]
Sir I extract data-set one file '' 20bn-something-something-v2-00'' using linux  it contain videos , I provided path to this folder in config file ,but this time I got this error again , Please suggest me something
**Traceback (most recent call last):
  File "C:/Users/Bilal/PycharmProjects/FYP/Main1.py", line 76, in <module>
    input_data, target, item_id = val_data[selected_indx]
  File "C:\Users\Bilal\PycharmProjects\FYP\data_loader_av.py", line 47, in __getitem__
    reader = av.open(item.path)
  File "av\container\core.pyx", line 226, in av.container.core.open
  File "av\container\core.pyx", line 148, in av.container.core.Container.__cinit__
  File "av\container\core.pyx", line 180, in av.container.core.Container.err_check
  File "av\utils.pyx", line 107, in av.utils.err_check
av.AVError: [Errno 2] No such file or directory: 'D:/20bn-something-something-v2\\166241.webm'**

**Comment by mehar50** [comment]
Sir please help me I am facing this from last week,I got error in this line : code
selected_indx = np.random.randint(len(val_data))
#selected_indx = 136
input_data, target, item_id = val_data[selected_indx]
error
**Traceback (most recent call last):
  File "C:/Users/Bilal/PycharmProjects/FYP/Main1.py", line 77, in <module>
    input_data, target, item_id = val_data[selected_indx]
  File "..\data_loader_av.py", line 47, in __getitem__
    reader = av.open(item.path)
  File "av\container\core.pyx", line 226, in av.container.core.open
  File "av\container\core.pyx", line 148, in av.container.core.Container.__cinit__
  File "av\container\core.pyx", line 180, in av.container.core.Container.err_check
  File "av\utils.pyx", line 107, in av.utils.err_check
av.AVError: [Errno 2] No such file or directory: 'D:\\20bn-something-something-v2\\39783.webm'**

Please help me to understand what is ''Selected index" because I opened the folder and putt the number here that is name of video that is present in folder but again it show this error ,,
